### PR TITLE
Upgrade to ZGW APIs version 1.1

### LINKED ISSUE #1109: As developer, I want Open Zaak to support ZGW APIs 1.1
**Changes per API**

Zaken API:
- [ ] ZaakContactMomenten resource added
- [ ] KlantContact resource deprecated
- [ ] ZaakVerzoek resource added
- [ ] ETag caching and HEAD operation added for:
  - [ ] Zaak
  - [ ] ZaakEigenschap
  - [ ] Resultaat
  - [ ] Rol
  - [ ] Status
  - [ ] ZaakInformatieObject
  - [ ] ZaakContactMoment
  - [ ] ZaakVerzoek
- [ ] `zaken.geforceerd-bijwerken` removed?
  - [ ] klantcontact
  - [ ] resultaten
  - [ ] rollen
  - [ ] ZIO POST
  - [ ] zaakobjecten
  - [ ] zaakeigenschap POST
- [ ] rol__betrokkenetype filter removed?
- [ ] zaak POST/PUT description changed?
- [ ] archiefnominatie/archiefstatus enum removed? max_length 1?

Catalogi API:
- [ ] ETag caching added

Documenten API:
- [ ] ETag caching added

Besluiten API:
- [ ] ETag caching added

Autorisaties API:
- [ ] ...

### PR DESCRIPTION
**Pull request by stevenbal**
Fixes #1109

**Changes**
* Bump vng-api-common to 1.7.7
* Fix API spec generation for newest vng-api-common
* Regenerate API specs
  * ~~Seems to add caching headers regardless of whether resource implements caching or not?~~
  * ~~Adds full API version (v1 -> v1.1.0) to `servers`?~~ fixed
* Add `ZaakContactMoment` resource
* Add `ZaakVerzoek` resource
* Caching

### CODE REVIEW

**Comment by sergei-maertens** [comment]
Rebased on main so that we're building on Django 3.2 for this :)

**Review by sergei-maertens — CHANGES_REQUESTED** [review]
I'm seeing HEAD operations that are missing ETag response header documentation (ZIO HEAD for example)

**Comment by stevenbal** [comment]
@sergei-maertens is there anything else I can do for this release?

**Comment by sergei-maertens** [comment]
> @sergei-maertens is there anything else I can do for this release?

Currently we're on hold - Sonny will be looking into the missing releases for the standard/reference implementations and then we can start taking those in too.

**Comment by sergei-maertens** [comment]
The plan now is to keep this PR limited to Zaken and Catalogi API - the upstream bugfixes are added as release blockers in #1183

**Comment by sergei-maertens** [comment]
build is failing because the test suite cherry pick for `ztc-010h` was not done on the stable-1.1.0 branch yet. Fixed that, so I'm now triggering a new build.

**Pull request merged**
