### PR TITLE
Fixes #726 Incorrect Rol filter parameter name

### LINKED ISSUE #726: Incorrect Rol filter parameter name
**Describe the bug**

See upstream bug: https://github.com/VNG-Realisatie/gemma-zaken/issues/1685

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #726 

Corrected the filter name and regenerated the schemas

Needs:

- [x] entry with the release notes -> tracks upstream API spec 1.0.x
- [x] unit test
- [x] Bump Zaken API version number

### CODE REVIEW

**Review by sergei-maertens — APPROVED** [review]
Apparently there are no tests for this filter?

**Comment by sergei-maertens** [comment]
This is still pending the upstream standard bugfix for the 1.0.x line of the standard.

**Comment by joeribekker** [comment]
This feature is ahead of a patch release of the Zaken API but will be in 1.0.3. See here: https://github.com/VNG-Realisatie/gemma-zaken/issues/1685

**Comment by sergei-maertens** [comment]
Needs:

- [ ] entry with the release notes -> tracks upstream API spec 1.0.x

**Comment by sergei-maertens** [comment]
1.0.3 of the standard is now out and includes this fix, so it'll go in 1.4.0 of Open Zaak

We'll get #912 merged first and then rebase this on main.

**Review by sergei-maertens — APPROVED** [review]

**Pull request merged**
