### PR TITLE
[#1817] Update open-api-framework

### LINKED ISSUE #1817: Update open-api-framework and make the usersessions visible
### Thema / Theme

Other

### Omschrijving / Description

For the session profile update an update to open-api-framework 0.9 is required.

Next to this, the admin-index fixture also needs updating: "SessionProfile admin should be added to admin index and its fixture."

### Toegevoegde waarde / Added value

_No response_

### Aanvullende opmerkingen / Additional context

_No response_

### PR DESCRIPTION
**Pull request by alextreme**
Fixes #1817

Do note that updating the fixture is still necessary: "SessionProfile admin should be added to admin index and its fixture."

### CODE REVIEW

**Comment by alextreme** [comment]
@annashamray see if it's possible to get this into the next OZ release icw Conor

**Review by annashamray — APPROVED** [review]

**Comment by annashamray** [comment]
@Coperh Could you please take a look? This issue blocks OZ release

**Review by Coperh — APPROVED** [review]
Looks good.

I wonder why the solo_cache is now needed

**Comment by annashamray** [comment]
@Coperh `SOLO_CACHE` setting was added in OAF 0.9.0, it was turned off before and now it caches django_solo values, which was not expected in the old tests

**Pull request merged**
