### PR TITLE
:arrow_up: [#1597] update to django 4.2

### LINKED ISSUE #1597: Update to Django 4.2 in Open Zaak
This depends on OAf library.

Tasks:
* [x] Update drc-cmis https://github.com/open-zaak/cmis-adapter/pull/82
* [x] Update django-loose-fk https://github.com/maykinmedia/django-loose-fk/pull/33
* [x] Update related dependencies in Open Zaak - https://github.com/open-zaak/open-zaak/pull/1614
* [x] Update code using Django 4.2 and python 3.10 syntax - #1634

### PR DESCRIPTION
**Pull request by annashamray**
Fixes #1597 (OZ part)

### CODE REVIEW

**Review by SonnyBA — APPROVED** [review]
Looks good to me :+1: . Note that it might be worthwhile to update `psycopg2` to `psycopg` as it will get deprecated as some point [according to the release notes](https://docs.djangoproject.com/en/5.0/releases/4.2/#psycopg-3-support).

**Comment by Coperh** [comment]
Screenshot from 2024-04-26 15-48-16

Help text button not aligned correctly

**Review by Coperh — CHANGES_REQUESTED** [review]
Basically already reviews this from #1614,

But everything seems to work correctly, except the front end formatting

**Review by bart-maykin — APPROVED** [review]

**Comment by annashamray** [comment]
@Coperh helptext should look prettier now and the dark theme should work

**Review by Coperh — APPROVED** [review]
Looks good on the website and as far as I can tell, the frontend code seems fine.

**Comment by annashamray** [comment]
@Coperh Thanks for the thorough check!

**Pull request merged**
