### PR TITLE
besluiten list api optimization

### LINKED ISSUE #1400: Improve performance in Besluiten-list
Version: [1.8.2-performance-fixes](https://github.com/open-zaak/open-zaak/releases/tag/1.8.2-performance-fixes)

Both Besluiten and EnkelvoudigInformatieobject, retrieve a Zaak for each Besluit/EIO. This should be optimized with a prefetch/select related:

You can see this behaviour here (for a list of 100 besluiten, it does 100x 1 query for each related zaak):

image

No prefetch:

image

Caused by the `__init__` method:

image

### PR DESCRIPTION
**Pull request by annashamray**
Fixes #1400

### CODE REVIEW

**Review by joeribekker — CHANGES_REQUESTED** [review]
I think this is the wrong direction entirely.

Why not simply:

```python
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._previous_zaak_id = self._zaak_id  # Store the already fetched ID
        self._previous_zaak_url = self._zaak_url
```

and 

```python
    @property
    def previous_zaak(self):
        if self._previous_zaak_id:
            return Zaak.objects.get(pk=self._previous_zaak_id)  # Retrieve Zaak based on previous ID

        if self._previous_zaak_url:
            remote_model = apps.get_model("zaken", "Zaak")
            return AuthorizedRequestsLoader().load(
                url=self._previous_zaak_url, model=remote_model
            )

        return None
```

change one unit test and done?

**Comment by annashamray** [comment]
@joeribekker Thank you for the simpler solution. I've checked it locally and it doesn't hit DB now, I've replaced the previous solution with the new one

**Review by joeribekker — CHANGES_REQUESTED** [review]
Can you add a test that shows that the if-statement for max_vertrouwelijkheid is solved.

**Comment by annashamray** [comment]
@joeribekker the regression test is added

**Review by joeribekker — APPROVED** [review]

**Pull request merged**
