### PR TITLE
:sparkles: [#1075] Extra filter options for Zaak.rol__betrokkeneIdentificatie

### PR DESCRIPTION
**Pull request by stevenbal**
PR in upstream has been merged: https://github.com/VNG-Realisatie/zaken-api/pull/208

Fixes https://github.com/open-zaak/open-zaak/issues/1075

**Changes**
* Added five extra filters for Zaken endpoint:
  * rol__betrokkeneIdentificatie__natuurlijkPersoon__anpIdentificatie
  * rol__betrokkeneIdentificatie__natuurlijkPersoon__inpA_nummer
  * rol__betrokkeneIdentificatie__nietNatuurlijkPersoon__innNnpId
  * rol__betrokkeneIdentificatie__nietNatuurlijkPersoon__annIdentificatie
  * rol__betrokkeneIdentificatie__vestiging__vestigingsNummer

### CODE REVIEW

**Comment by stevenbal** [comment]
> Am I correct that this is a Zaken API 1.1 or 1.2 thing?

I think so yes, these weren't part of Zaken API before, so I guess it's part of 1.2? @alextreme

**Comment by alextreme** [comment]
@stevenbal the zaken-api PR was merged end November 2021and there hasn't been a release since then, so this most will likely be part of Zaken API v1.3. Check with Sonny if there's a release planned.

**Comment by sergei-maertens** [comment]
For that reason I've marked the PR as draft now :-)

**Review by annashamray — COMMENTED** [review]
Looks good! 
Could you please rebase it on main? To make sure that CI passes

**Comment by annashamray** [comment]
A new PR #1444 with rebased commits is created

**Pull request closed without merging**
